# .github/workflows/main.yml

name: My Email Action

# This action will trigger on every push to the repository
on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This step checks out your repository's code so the workflow can access it
      - uses: actions/checkout@v3

      # This is the required step with your email address in the name
      - name: 23f1001630@ds.study.iitm.ac.in
        run: echo "Hello, world! This action ran successfully."
